### ISSUE TITLE
Verified bot user group missing on fast chat section

### ISSUE THREAD

**Issue by TETYYS** [pajbot/tmi-rate-limits#5]
In section `Twitch limits the speed of really fast chats by dropping messages if they exceed a per-channel rate limit bucket of unknown refill rate and unknown refill amount. If you send a message while this bucket is drained, your message is not delivered to chat (it is dropped). Moderators, VIPs and Broadcasters are exempt from this.` "verified bots" is missing besides mods, vips and broadcasters.

**Comment by RAnders00** [comment]
Good report, has been fixed.
